development:
  adapter: postgresql
  encoding: unicode
  database: challah_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: challah_test
  pool: 5
  min_messages: warning